--- #YAML:1.0
name:                Authen-Krb5-Simple
version:             0.43
abstract:            Perl module that performs Kerberos 5 authentication
license:             ~
author:              
    - Damien S. Stuart <dstuart@dstuart.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
